### ISSUE TITLE
cant be used with dovecot lua plugins ?

### ISSUE THREAD

**Issue by elhakimz** [chensoft/lua-kafka#1]
Hello, 
I am using dovecot as my email server , and also install lua 5.3  and lua push notification for dovecot
currently I am testing your lua-kafka library but it found the error:

Error: imap(abiel)<22><1giUJSj1YN/AqDAB>: lua: lua_pcall(/etc/dovecot/scripts/dovecotkafkapush.lua) failed: error loading module 'kafka' from file '/usr/local/lib/lua/5.3/kafka.so':
Feb 20 21:14:21 Error: imap: 	/usr/local/lib/lua/5.3/kafka.so: undefined symbol: luaL_checkversion
Feb 20 21:14:21 Error: imap: stack traceback:
Feb 20 21:14:21 Error: imap: 	[C]: in ?
Feb 20 21:1
[dovecotkafkapush .lua.txt](https://github.com/chensoft/lua-kafka/files/10787832/dovecotkafkapush.lua.txt)
4:21 Error: imap: 	[C]: in function 'require'
Feb 20 21:14:21 Error: imap: 	/etc/dovecot/scripts/dovecotkafkapush.lua:7: in main chunk

and this is my push notification code using lua-kafka

how can I resolve this?  I want to use kafka rather than http push method

thanks for your assistance

**Comment by chensoft** [comment]
You need to install liblua5.3-dev
