### ISSUE TITLE
always pointing kafka server to localhost

### ISSUE THREAD

**Issue by elhakimz** [chensoft/lua-kafka#2]
Hello I am testing this library against a kafka Ip , but it always pointing to localhost

local settings = {["bootstrap.servers"] = "192.168.128.4"}
local producer = require("kafka").producer(settings)

for i = 1, 100 do
    print("send message " .. i)
    producer:produce("hello1", "Hello World! " .. i)
    producer:produce("hello2", i .. " Hello World!")
end

producer:poll(5000)
producer:close()

---
send message 98
send message 99
send message 100
%3|1677501106.503|FAIL|rdkafka#producer-1| [thrd:localhost:9092/1]: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 1ms in state CONNECT)
%3|1677501106.504|ERROR|rdkafka#producer-1| [thrd:app]: rdkafka#producer-1: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 1ms in state CONNECT)
%4|1677501106.504|TERMINATE|rdkafka#producer-1| [thrd:app]: Producer terminating with 200 messages (2984 bytes) still in queue or transit: use flush() to wait for outstanding message delivery

the topic is listed , but the messages are empty
<img width="1391" alt="Screen Shot 2023-02-27 at 19 35 58" src="https://user-images.githubusercontent.com/616176/221565605-9377a64b-879f-42a5-8752-09faa86663e9.png">

| [2023-02-27 12:35:42,317] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper)
schema-registry       | io.confluent.rest.exceptions.RestNotFoundException: Subject 'hello1-value' not found.

**Comment by chensoft** [comment]
Hello, I am unable to reproduce the error on macOS and Debian, which OS and Version do you use?
The source code is very simple, you can also clone and compile it on your machine to debug issues.

**Comment by elhakimz** [comment]
hi, currently I use it inside dovecot which placed in a docker container, and try to make a lua script for push-notification to kafka  instead http endpoint

if I ping kafka "broker" inside from dovecot shell, it will response pointing to kafka server , but if I run the producer or consumer example. it always pointing to  "localhost" even if I declare bootstrap server  with  IP address or host name

local settings = {["bootstrap.servers"] = "broker"}

here is my docker-compose which I use

 
[docker-compose.yml.txt](https://github.com/chensoft/lua-kafka/files/10843943/docker-compose.yml.txt)

**Comment by elhakimz** [comment]
solved:
should define the bootstrap servers with exposed port

local settings = {["bootstrap.servers"] = "broker:29092"}

it works now,

thank you for your assistance.

**Comment by chensoft** [comment]
Thank you, I will fix the example.
