### ISSUE TITLE
`kafka.producer` returns nil on command line

### ISSUE THREAD

**Issue by pushpesh-cometchat** [chensoft/lua-kafka#3]
Installed it via `luarocks`.

When testing on command line, when I run the below code:

```
kafka = require('kafka')

settings = {['bootstrap.servers'] = 'CLUSTER_IPS'}

producer = kafka.producer(settings)

print(producer) ----> returns nil
```

However, putting this same code in a `.lua` file and running it via `lua file.lua` works. Any idea why that might be.

Lua version - 5.4.6
Luarocks version - 3.9.2
OS - MacOS

**Comment by chensoft** [comment]
You can try the following code, it will print any errors if they occur:

kafka = require('kafka')
settings = {['bootstrap.servers'] = 'CLUSTER_IPS'}
kafka.producer(settings)

Do not assign result to producer, just call kafka.producer in command line.

However, it works fine on my macbook:

Apple M1
macOS 13.4
Lua 5.4.6
Luarocks 3.9.2
lua-kafka 1.0.0-3
librdkafka 2.1.1

**Comment by pushpesh-cometchat** [comment]
Thanks for replying. But when I do `kafka.producer(settings)`, it throws the below error. Also, how would I produce a message if I don't get a reference to the producer.

> nil	val must be a string

My code:

> kafka = require('kafka')
inspect = require('inspect')

> settings = {['bootstrap.servers'] = 'CLUSTER_IPS'}

> print(inspect(settings))
{
  ["bootstrap.servers"] = "CLUSTER_IPS"
}
> print(inspect(kafka))
{
  consumer = <function 1>,
  producer = <function 2>
}
> kafka.producer(settings)
nil	val must be a string

**Comment by chensoft** [comment]
"val must be a string" means 'CLUSTER_IPS' is not a string...

**Comment by chensoft** [comment]
producer, error = kafka.producer(settings)
You can get the producer and the error message.

**Comment by pushpesh-cometchat** [comment]
`"val must be a string" means 'CLUSTER_IPS' is not a string...
`
But it is. This worked.

> kafka = require('kafka')
> settings={["acks"] = "all",["batch.size"] = 10,["bootstrap.servers"] = "localhost:9092",["client.id"] = "calls",["compression.type"] = "gzip",["enable.idempotence"] = 1,["linger.ms"] = 5,["max.in.flight.requests.per.connection"] = "5"}
> p = kafka.producer(settings)
> p:produce('test', 'test123')
> true

Thanks
